name: C/C++ (meson) CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Meson Build
      # You may pin to the exact commit or the version.
      # uses: BSFishy/meson-build@656b2a360964b249ac82905a52018921e01d875b
    - uses: BSFishy/meson-build@v1.0.3
    - uses: actions/checkout@v4
    - name: build
      run: meson setup build/
    - name: compile
      run: meson compile -C build/
